# -*- coding: utf-8 -*-
"""Last squares Optimization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_JCsVmQSs-wSyFvNd7M11zrcSlGh1bkZ
"""

x = [12,16,71,99,45,27,80,58,4,50]
y = [56,22,37,78,83,55,70,94,12,40]

xy = []
for i, val in enumerate(x):
    xy.append(x[i] * y[i])

x_sqrt = [i**2 for i in x]
n = len(x)
w = (n*sum(xy) - sum(x)*sum(y)) / (n+sum(x_sqrt)-sum(x)**2)
b = (sum(y) - w*sum(x))/n

print(w,b)

from sklearn.linear_model import LinearRegression
import numpy as np

x = [12,16,71,99,45,27,80,58,4,50]
y = [56,22,37,78,83,55,70,94,12,40]

x = np.array(x).reshape(-1,1)
y = np.array(y).reshape(-1,1)

linreg = LinearRegression().fit(x,y)
print(linreg.coef_, linreg.intercept_)

import matplotlib.pyplot as plt

plt.scatter(x,y)
ax = plt.gca()
ax.set_xlabel('x')
ax.set_ylabel('y')
plt.plot(x,linreg.intercept_+linreg.coef_*x, color='r')

